<?php


class codeGenerator {

    public function createProperties(){

        if( isset( $_POST['generate_codes'] ) && isset( $_POST['codes_number'] ) ){

            $codesNumber = intval( $_POST['codes_number'] );

            if( $codesNumber > 0 ) {

                for ( $x = 1; $x <= $codesNumber; $x++ ) {

                    $property = array(
                        'post_title' => "#$x Auto-generated draft property",
                        'post_content' => "This is an autogenerated property to create a code",
                        'post_status' => 'draft',
                        'post_type' => 'property',
                        'post_author' => 1,
                    );

                    $code = wp_insert_post($property, true);

                    if (!$code instanceof WP_Error) {

                        // Update post
                        $property = array(
                            'ID' => $code,
                            'post_title' => "Property Code: $code", // new title
                        );

                        // Update the post into the database
                        wp_update_post($property);

                    }

                }

            }

        }

    }


    public function getGeneratedCodes(){

        $ids = array();

        $args = array(
            'post_type'         => 'property',
            'post_status'       => 'draft',
            'posts_per_page'    => -1,
            's'                 => 'Property Code:',
        );

        $query = new WP_Query( $args );

        if( $query->have_posts() ){

            while ( $query->have_posts() ) {
                $query->the_post();
                $ids[] = get_the_ID();
            }

        }

        return $ids;

    }

}
