<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class ExcelExportController
{

    public function generate_interests_excel(){

        $interestRequest = new Homi_Addons_Interest_Request();
        $requests = $interestRequest->get_non_abandoned_interest_requests();

        $today                          = date('d-m-Y.H:i');
        $file_name                      = 'interest.requests.'. $today .'.xlsx';
        $uploads_dir                    = wp_upload_dir();
        $server_excel_folder            = $uploads_dir['basedir'] . '/homi-excel/';
        $public_excel_folder            = $uploads_dir['baseurl'] . '/homi-excel/';

        $phpExcel = new Spreadsheet();

        $phpExcel->getProperties()->setCreator('HOMI')
            ->setTitle('Interest Requests - ' . $today )
            ->setSubject('Interest Requests')
            ->setDescription('All the interest requests made on HOMI website until ' . $today );


        $phpExcel->getActiveSheet()->setTitle("Autogenerated Data");
        $phpExcel->setActiveSheetIndex(0)
            ->setCellValue('A1','ID')
            ->setCellValue('B1','User Name')
            ->setCellValue('C1','User Email')
            ->setCellValue('D1','Area 1')
            ->setCellValue('E1','Area 2')
            ->setCellValue('F1','Area 3')
            ->setCellValue('G1','Min. Size(sqm)')
            ->setCellValue('H1','Min. Bedrooms')
            ->setCellValue('I1','Max Price')
            ->setCellValue('J1','Request URL')
            ->setCellValue('K1','User URL')
            ->setCellValue('L1','Date')
        ;


        $col = 2;
        /** @var $request RentInterest */
        foreach ( $requests as $request) {
            $phpExcel->setActiveSheetIndex(0)
                ->setCellValueByColumnAndRow( 1 , $col , $request->ID )
                ->setCellValueByColumnAndRow( 2 , $col , $request->user->first_name . ' ' . $request->user->last_name )
                ->setCellValueByColumnAndRow( 3 , $col , $request->user->user_email )
                ->setCellValueByColumnAndRow( 4 , $col , $request->area_1 )
                ->setCellValueByColumnAndRow( 5 , $col , $request->area_2 )
                ->setCellValueByColumnAndRow( 6 , $col , $request->area_3 )
                ->setCellValueByColumnAndRow( 7 , $col , $request->min_size )
                ->setCellValueByColumnAndRow( 8 , $col , $request->min_bedrooms )
                ->setCellValueByColumnAndRow( 9 , $col , $request->max_price )
                ->setCellValueByColumnAndRow( 10 , $col , $request->url )
                ->setCellValueByColumnAndRow( 11 , $col , $request->user_url )
                ->setCellValueByColumnAndRow( 12 , $col , $request->date )
            ;

            $phpExcel->setActiveSheetIndex(0)->getCellByColumnAndRow( 10 , $col )->getHyperlink()->setUrl($request->url);
            $phpExcel->setActiveSheetIndex(0)->getCellByColumnAndRow( 11 , $col )->getHyperlink()->setUrl($request->user_url);

            $col++;
        }


        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('A')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('B')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('C')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('D')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('E')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('F')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('G')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('H')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('I')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('J')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('K')->setAutoSize(true);
        $phpExcel->setActiveSheetIndex(0)->getColumnDimension('L')->setAutoSize(true);

        try{

            $writer = new Xlsx($phpExcel);
            $writer->save( $server_excel_folder . $file_name );

            ?>

            <div class="excel-success">
                <p>Your Excel file with the Interest Requests data has been created. Click on the button below to download it.</p>
                <a href="<?php echo $public_excel_folder . $file_name; ?>" download>
                    Download excel file
                </a>
            </div>

            <?php


        }
        catch (\PhpOffice\PhpSpreadsheet\Writer\Exception $e) {

            echo 'There was an error while creating the excel file';

        }


    }

}
